# Generated by Django 5.1.5 on 2025-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_categor_4083ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_color_e898d3_idx",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="collection",
            field=models.CharField(
                choices=[("tshirts", "T-Shirts"), ("hoodies", "Hoodies")],
                default="tshirts",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.JSONField(default=list, help_text="List of available colors"),
        ),
        migrations.AddField(
            model_name="product",
            name="design_theme",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="fabric",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="gsm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="printing_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(default="Active", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("user", "product", "size", "color")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["collection"], name="products_collect_fc9dc4_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
